### ISSUE TITLE
merge some of mjpost's new features

### ISSUE THREAD

**Issue by shuoyangd** [shuoyangd/tape4nmt#13]
@mjpost do you mind submitting your current master branch as a pull request and let me merge in some features on top of that?

Despite the fact that I don't want to get rid of `dummy*` and I don't like the new dataset naming scheme, lots of new features (e.g. downloading from `sacrebleu://`, lowercase, source factor) actually look really cool, and it seems easier to work on top of it than individually copying each part.

Thanks!

**Comment by mjpost** [comment]
You just want me to submit my current master against your current master?

**Comment by shuoyangd** [comment]
Yep. Seems like it'll be quite a lot diff, but I'll sort it out.

**Comment by shuoyangd** [comment]
Ah, I think it's the same if I checkout your master and push to this repo. No need for pull request.
