### ISSUE TITLE
add sockeye support

### ISSUE THREAD

**Issue by shuoyangd** [shuoyangd/tape4nmt#3]

**Comment by mjpost** [comment]
This was added in b8ade9b06638752b912372f036285fb24c8d6bf9.

**Comment by shuoyangd** [comment]
Did you test that with the IWSLT setting? What BLEU score did you get?

**Comment by mjpost** [comment]
No, I just run a limited “test” plan that just demonstrates that the workflow works. I’ll run a full one tomorrow if you’re curious.

**Comment by shuoyangd** [comment]
Yeah would be nice if workflow contains a reasonable hyper-parameter setting out-of-the-box.
