### ISSUE TITLE
add SacreBLEU support

### ISSUE THREAD

**Issue by shuoyangd** [shuoyangd/tape4nmt#4]

**Comment by mjpost** [comment]
@shuoyangd: SacreBLEU will remove XML from dev and test data, and will score without having to rewrap them. Are you okay if I remove these tasks as part of the sacrebleu branch?

**Comment by shuoyangd** [comment]
I would rather keep the pipeline backward-compatible if possible. If you want to use original dev/test reference, maybe it's better to just take `$out@download_or_link[DevtestDataSection:dev,side:trg]` as input of the sacrebleu task?

**Comment by shuoyangd** [comment]
Solved by #6. Cheers!
