### ISSUE TITLE
Package parameters must be literals

### ISSUE THREAD

**Issue by mjpost** [shuoyangd/tape4nmt#7]
It seems one of us (was it you?) added environment loading into packages. This doesn't seem to work in a nice way, though—apparently package arguments cannot be variables, so you can't specify your Python environment in the top-level file and have it be passed in to the package.

I don't see any reason for this, but it really restricts our ability to install code in an environment

**Comment by mjpost** [comment]
Here is my suggestion for how we should handle this. The versioners (pip and git) and submitters (shell and sge) should load the environment from ~/.ducttape.env, if it exists.

**Comment by mjpost** [comment]
This is solved by commit 46df6b94e98b7c4e173468d627b8cc7aea1e753e. The short answer is:

- "submitters" can load the environment, since they can receive $pyenv as an argument.
- versioners and packages cannot load the environment in an easy way, in part because duct tape isn't designed for this. However, there is a simple workaround: versioning and package installation is run on the head node (wherever ducttape is called), so it is a simple matter to just call ducttape from within the environment you want everything installed to. Then these tools will be available to the submitters (shell and sge), so long as you set `$pyenv` correctly.

I think this is the right solution.

**Comment by shuoyangd** [comment]
Makes sense. Though I vaguely remember something like that wasn't working for me previously. I'll reopen this issue if something pops up.
